Traceback (most recent call last):
  File "/Users/kstlaurent/anaconda3/envs/SCDA2/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: PyCapsule_Import could not import module "datetime"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/user/kstlaurent/git/progressive_refinement_coronagraphy/surveys/luvoir_N0200_small_local/drivers/09_LUVOIR_N200_FPM382M050_IWA0300_OWA01200_C10_BW18_Nlam8_LS_IDD0191_OD0946_no_ls_struts.py", line 5, in <module>
    from hcipy import *
  File "/Users/kstlaurent/git/hcipy/hcipy/__init__.py", line 2, in <module>
    from . import aperture
  File "/Users/kstlaurent/git/hcipy/hcipy/aperture/__init__.py", line 4, in <module>
    from .generic import *
  File "/Users/kstlaurent/git/hcipy/hcipy/aperture/generic.py", line 2, in <module>
    import numpy as np
  File "/Users/kstlaurent/anaconda3/envs/SCDA2/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/Users/kstlaurent/anaconda3/envs/SCDA2/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/Users/kstlaurent/anaconda3/envs/SCDA2/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/Users/kstlaurent/anaconda3/envs/SCDA2/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/Users/kstlaurent/anaconda3/envs/SCDA2/lib/python3.6/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: PyCapsule_Import could not import module "datetime"

